sudo: required
services:
  - docker
before_install:
  - docker build -t thanhm963/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thanhm963/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-767398048409"
  bucket_path: "frontend"
  on:
    repo: thanhm963/docker-react
    branches:
      only:
        - master
  access_key_id: $AWS_ACCESS_KEY

  secret_access_key: "$AWS_SECRET_KEY"
