sudo: required
services:
  - docker
before_install:
  - docker build -t thanhma/docker-react -f Dockerfile.dev .

script:
  - docker run thanhma/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-767398048409"
  bucket_path: "frontend"
  on: branch:master
  access_key_id: $AWS_ACCESS_KEY

  secret_access_key: $AWS_SECRET_KEY
